name: Build diudiu frontend docker image

on:
  push:
    tags:
      - diudiu-frontend@*
jobs:
  build-diudiu-frontend:
    runs-on: ubuntu-latest
    steps:
      # 設定環境
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 建置和推送
      - name: Get Version
        run: |
          export VERSION=${GITHUB_REF#refs/*/*@}
          echo "::env VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build diudiu-frontend image
        run: |
          docker build \
          --file build/diudiu-frontend.Dockerfile \
          --tag marco79423/diudiu-frontend:latest \
          .

      - name: Push diudiu-frontend image
        run: |
          echo "::env VERSION=${{env.VERSION}}"

          docker push marco79423/diudiu-frontend:latest

          docker tag marco79423/diudiu-frontend:latest marco79423/diudiu-frontend:${{env.VERSION}}
          docker push marco79423/diudiu-frontend:${{env.VERSION}}
